[package]
authors = ["David Flemström <david.flemstrom@gmail.com>"]
build = "build.rs"
description = "Low-level bindings to V8, the Javascript engine"
include = ["build.rs", "src/**/*", "Cargo.toml"]
keywords = ["v8", "javascript", "js", "ecmascript", "google"]
name = "v8-sys"
license = "Apache-2.0"
repository = "https://github.com/dflemstr/v8-rs/tree/master/v8-sys"
version = "0.1.0"

[build-dependencies]
bindgen = "0.19.0"
clang = "0.12.0"
gcc = "0.3.35"
v8-api = "0.1.0"

[dev-dependencies]
lazy_static = "0.2.1"

[features]
shared = []
